Updated Readme for Effective Reading
ArkScript-lang/Ark pull request #160
Opened 2020-09-30 18:40 UTC by Piyussshh

Changed 
1. "Term"  to "Terms"  
2. "object oriented"  to "object-oriented"
3. "less" to "fewer"

2020-09-30 18:44 UTC, SuperFola requested changes

2020-09-30 18:44 UTC, SuperFola commented on README.md
> +* small: the compiler and the virtual machines fit under 5000 lines, but also small in terms of keywords (it has only 10)!
Just a small comment but you couldn't know (and I'm taking the opportunity to hit two birds in one stone): it's 8000 lines now, not 5000

2020-10-01 14:57 UTC, Piyussshh commented
Yes?

2020-10-01 15:18 UTC, Piyussshh commented
> @Piyussshh ?

Yes? @SuperFola

2020-10-01 15:29 UTC, Piyussshh commented
> Could you correct your PR according to the comments I left?

on it!

2020-10-01 16:08 UTC, SuperFola approved these changes

2020-10-01 16:09 UTC, merged