Build system
ArkScript-lang/Ark pull request #306
Opened 2021-09-21 00:09 UTC by SDAChess

This pull request introduces a lot of changes in the build system, division into git submodules a better install rule.

This is a starting point and I think some things could be improved but the overall structure is better.

2021-09-21 08:34 UTC, SuperFola requested changes

2021-09-21 08:34 UTC, SuperFola commented on CMakeLists.txt
> -    endif()
this is actually needed, at least on Ubuntu, otherwise it can't compile

2021-09-21 08:35 UTC, SuperFola commented
Also when reading the CI logs, seems like we need a -fPIC in the ArkString: https://github.com/ArkScript-lang/Ark/pull/306/checks?check_run_id=3660188801#step:6:62

2021-09-21 10:19 UTC, SDAChess commented
Ok this is worse than I expected, I don't know why there is so many errors. I'll try to fix this one today.

2021-09-23 09:58 UTC, SuperFola commented on CMakeLists.txt
> -set(CMAKE_POSITION_INDEPENDENT_CODE ON)
I would suggest adding this back

2021-09-27 12:20 UTC, SuperFola approved these changes

2021-09-27 12:41 UTC, merged